version: '3.7'
services:
  db:
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql

  admin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.1.1 
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    links:
      - db

volumes:
  mysql_data: